name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_arch: [aarch64, arm64, x86_64]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        sudo apt update && sudo apt install -y libpcap-dev
        go build -o phantomsocks-original -v ./...
        go build -o phantomsocks-pcap -v -tags pcap ./...
        go build -o phantomsocks-rawsocket -v -tags rawsocket ./...
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ps-${{ matrix.target_arch }}
        path: ./phantomsocks*
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build  -o phantomsocks-original -v ./...
        go build  -o phantomsocks-pcap -v -tags pcap ./...
        go build  -o phantomsocks-windivert -v -tags windivert ./...
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ps-${{ matrix.target_arch }}
        path: ./phantomsocks*
        
        
